# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: cd fgg-front-end && npm install
      - name: Build frontend
        run: cd fgg-front-end && npm run build
  build-backend:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install dependencies
          run: cd fgg-back-end
        - name: Oracledb
          run: cd fgg-back-end && npm uninstall oracledb && npm install oracledb && npm install
        - name: Build backend
          run: cd fgg-back-end && npm run server
